#### Get weather information using DarkSky API

In [13]:
import requests
import pandas as pd
from collections import namedtuple
from datetime import datetime

In [40]:
#Using UNIX time (01-07-2012 00:00:00, 02-07-2012 00:00:00, hourly)

def weather_info(start_t, end_t, lat, lon):
    df_0 = []
    params = [
        "time", #The UNIX time, seconds since midnight GMT on 1 Jan 1970
#         "summary", #Basically sunny, windy, rainy, cloudy,etc-Do we need this?
        "temperature", #Farenheit degrees(later convert to Celsius)
        "precipIntensity", #Volume mm if there is rain or snow
        "precipProbability", #Rain or snow probability
        "windSpeed", # Numerical value representing the wind speed in kilometers per hour
        "windGust", #Wind Gusts is a quick and sudden increase in the speed of wind
#         "windBearing", #Wind direction
#         "cloudCover",#Cloud percentage
#         "visibility",
        "humidity"
    ]
    
    #API_KEY this is jedha's api key. Need to ask.
    #Using lat,lon in Ausgrid data
    #-33.891348,151.191243
    
    HourlySummary = namedtuple("HourlySummary", params)
    
    #Daily
    for time_point in range(start_t,end_t,86400):#24h*3600seconds->1 day
        darksky_url="https://api.darksky.net/forecast/15074402c474e3dab67f7377e1f95519/" + str(lat) + "," + str(lon) + "," + str(time_point) + "?exclude=currently,flags,alerts,minutely,daily"
        response = requests.get(darksky_url)
        data = response.json()
        
        #Hourly
        for i in range(0,24): # 24 hours
            df_0.append(
                HourlySummary(
                    time=data['hourly']['data'][i]['time'],
#                   summary=data['hourly']['data'][i]['summary'],
                    temperature=data['hourly']['data'][i]['temperature'],
                    precipIntensity = data['hourly']['data'][i]['precipIntensity'],
                    precipProbability = data['hourly']['data'][i]['precipProbability'],
                    windSpeed = data['hourly']['data'][i]['windSpeed'],
                    windGust = data['hourly']['data'][i]['windGust'],
#                     windBearing = data['hourly']['data'][i]['windBearing'],
#                   cloudCover = data['hourly']['data'][i]['cloudCover'],
#                   visibility = data['hourly']['data'][i]['visibility'],
                    humidity = data['hourly']['data'][i]['humidity']
                )
            )

    #Convert to DataFrame
    df = pd.DataFrame(df_0, columns=params)

    #Convert UNIX datetime human-readable datetime
    df['time']=df['time'].apply(lambda x: datetime.utcfromtimestamp(int(x)).strftime('%Y-%m-%d %H:%M:%S'))

    #Convert sFarenheit to Celsius
    df['temperature'] = df['temperature'].apply(lambda x: (x-32)*5/9)

    #Write to csv files
    df.to_csv(str(lat) + str(lon) + str(unix_time) + str(duration_h) + ".csv", index=False)

In [ ]:
#Get information on one location 3 years data 
weather_info(start_t=1277913600, end_t=1372636800, lat=-32.580782, lon=151.127733)

In [86]:
df=pd.read_csv('dataset\-32.580782151.1277331277913600.csv')

26376

In [87]:
df

,time,temperature,precipIntensity,precipProbability,windSpeed,windGust,windBearing,humidity
0,2010-06-30 14:00:00,8.566667,0,0,8.73,9.75,315,0.68
1,2010-06-30 15:00:00,8.133333,0,0,13.60,15.57,315,0.68
2,2010-06-30 16:00:00,6.494444,0,0,9.72,10.70,315,0.73
3,2010-06-30 17:00:00,6.411111,0,0,6.68,7.79,316,0.75
4,2010-06-30 18:00:00,5.411111,0,0,2.96,3.96,270,0.78
5,2010-06-30 19:00:00,5.972222,0,0,8.88,10.86,315,0.77
6,2010-06-30 20:00:00,4.177778,0,0,0.98,1.98,90,0.81
7,2010-06-30 21:00:00,3.222222,0,0,2.96,3.96,0,0.86
8,2010-06-30 22:00:00,4.866667,0,0,1.98,2.96,135,0.82
9,2010-06-30 23:00:00,9.483333,0,0,6.01,6.01,299,0.68
10,2010-07-01 00:00:00,13.150000,0,0,9.76,11.78,270,0.56
11,2010-07-01 01:00:00,14.316667,0,0,7.83,10.84,0,0.54
12,2010-07-01 02:00:00,15.966667,0,0,8.77,10.84,315,0.49
13,2010-07-01 03:00:00,15.533333,0,0,8.83,10.85,270,0.49
14,2010-07-01 04:00:00,16.044444,0,0,8.79,11.82,0,0.47
15,2010-07-01 05:00:00,15.161111,0,0,7.40,10.84,292,0.45
16,2010-07-01 06:00:00,15.505556,0,0,3.92,4.98,292,0.47
17,2010-07-01 07:00:00,13.261111,0,0,1.95,1.95,315,0.57
18,2010-07-01 08:00:00,10.950000,0,0,3.74,3.93,315,0.67
19,2010-07-01 09:00:00,10.466667,0,0,2.91,3.91,315,0.68
20,2010-07-01 10:00:00,8.833333,0,0,0.97,2.00,270,0.73
21,2010-07-01 11:00:00,8.144444,0,0,3.04,3.91,355,0.79
22,2010-07-01 12:00:00,7.722222,0,0,1.95,1.98,180,0.80
23,2010-07-01 13:00:00,7.177778,0,0,0.97,1.98,45,0.84