In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates

In [2]:
daily=pd.read_csv("gg_gc_2012_customerID_11.csv", parse_dates=True)
weather=pd.read_csv("2012-2013_weather_final.csv", parse_dates=True)

In [3]:
print(daily.shape)
print(weather.shape)

(17520, 3)
(17520, 15)

In [4]:
daily.head()

                  date     GC   GG
0  2012-07-01 00:00:00  0.353  0.0
1  2012-07-01 00:30:00  0.567  0.0
2  2012-07-01 01:00:00  0.547  0.0
3  2012-07-01 01:30:00  0.613  0.0
4  2012-07-01 02:00:00  0.519  0.0

In [5]:
weather.head()

,zip_code,date,temperature,apparentTemperature,precipIntensity,precipProbability,dewPoint,humidity,pressure,windSpeed,windGust,windBearing,uvIndex,cloudCover,visibility
0,2026,2012-07-01 00:00:00,10.77,10.77,0.0,0.0,5.48,0.70,1014.8,0.75,0.75,294,0,0.78,9.988
1,2026,2012-07-01 00:30:00,10.77,10.77,0.0,0.0,5.48,0.70,1014.8,0.75,0.75,294,0,0.78,9.988
2,2026,2012-07-01 01:00:00,10.21,10.21,0.0,0.0,5.52,0.73,0.0,0.21,0.61,289,0,1.00,0.000
3,2026,2012-07-01 01:30:00,10.21,10.21,0.0,0.0,5.52,0.73,0.0,0.21,0.61,289,0,1.00,0.000
4,2026,2012-07-01 02:00:00,9.48,9.48,0.0,0.0,5.22,0.75,0.0,0.33,0.95,284,0,0.88,0.000

In [7]:
weather.drop(columns=["zip_code"], inplace=True)

In [8]:
df=weather.merge(daily, on='date', how='left')

In [9]:
df.head()

,date,temperature,apparentTemperature,precipIntensity,precipProbability,dewPoint,humidity,pressure,windSpeed,windGust,windBearing,uvIndex,cloudCover,visibility,GC,GG
0,2012-07-01 00:00:00,10.77,10.77,0.0,0.0,5.48,0.70,1014.8,0.75,0.75,294,0,0.78,9.988,0.353,0.0
1,2012-07-01 00:30:00,10.77,10.77,0.0,0.0,5.48,0.70,1014.8,0.75,0.75,294,0,0.78,9.988,0.567,0.0
2,2012-07-01 01:00:00,10.21,10.21,0.0,0.0,5.52,0.73,0.0,0.21,0.61,289,0,1.00,0.000,0.547,0.0
3,2012-07-01 01:30:00,10.21,10.21,0.0,0.0,5.52,0.73,0.0,0.21,0.61,289,0,1.00,0.000,0.613,0.0
4,2012-07-01 02:00:00,9.48,9.48,0.0,0.0,5.22,0.75,0.0,0.33,0.95,284,0,0.88,0.000,0.519,0.0

In [10]:
df.set_index('date', inplace=True)

In [11]:
df

,temperature,apparentTemperature,precipIntensity,precipProbability,dewPoint,humidity,pressure,windSpeed,windGust,windBearing,uvIndex,cloudCover,visibility,GC,GG
date,,,,,,,,,,,,,,,
2012-07-01 00:00:00,10.77,10.77,0.0000,0.00,5.48,0.70,1014.8,0.75,0.75,294,0,0.78,9.988,0.353,0.000
2012-07-01 00:30:00,10.77,10.77,0.0000,0.00,5.48,0.70,1014.8,0.75,0.75,294,0,0.78,9.988,0.567,0.000
2012-07-01 01:00:00,10.21,10.21,0.0000,0.00,5.52,0.73,0.0,0.21,0.61,289,0,1.00,0.000,0.547,0.000
2012-07-01 01:30:00,10.21,10.21,0.0000,0.00,5.52,0.73,0.0,0.21,0.61,289,0,1.00,0.000,0.613,0.000
2012-07-01 02:00:00,9.48,9.48,0.0000,0.00,5.22,0.75,0.0,0.33,0.95,284,0,0.88,0.000,0.519,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-06-30 21:30:00,12.70,12.70,0.0713,0.31,11.49,0.92,1024.7,1.48,1.74,237,0,0.42,10.003,0.404,0.000
2013-06-30 22:00:00,12.21,12.21,0.0056,0.04,11.12,0.93,1024.7,1.42,2.11,248,0,0.40,10.003,0.747,0.000
2013-06-30 22:30:00,12.21,12.21,0.0056,0.04,11.12,0.93,1024.7,1.42,2.11,248,0,0.40,10.003,0.656,0.001
2013-06-30 23:00:00,11.70,11.70,0.0000,0.00,10.52,0.92,0.0,1.05,3.44,261,0,0.19,10.003,0.291,0.000
2013-06-30 23:30:00,11.70,11.70,0.0000,0.00,10.52,0.92,0.0,1.05,3.44,261,0,0.19,10.003,0.230,0.000

In [12]:
#Export into CSV
df.to_csv("2012_2013_merged_customerID_11.csv")